# Theming
include theme.conf

# Font
font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 9.0

# Cursor
cursor_shape beam
cursor_trail 1

# Padding (why weird value? consistency with foot)
window_margin_width 10

# No stupid close confirmation
confirm_os_window_close 0

# Use zsh shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt