$lock_cmd = hyprctl dispatch 'hl.dsp.global("donwaztok:lock")'

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = $lock_cmd
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.global("donwaztok:lockFocus")' && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    on_unlock_cmd = hyprctl dispatch 'hl.dsp.force_idle(0)'
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = $lock_cmd
}

listener {
    timeout = 600 # 10mins
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
