-- Hyprland Lua configuration (0.55+)
-- https://wiki.hypr.land/Configuring/Start/
--
-- Do NOT keep hyprland.conf in this folder — Hyprland may fall back to the
-- autogenerated stub and ignore most of this config.

-- Required for Quickshell global keybinds / catchall behavior
hl.exec_cmd("hyprctl dispatch submap global")

-- 1. Environment
require("lua.hyprland.env")
require("lua.custom.env")

-- 2. Hardware layout (nwg-displays: edit lua/machine/*.lua after changes)
require("lua.machine.monitors")
require("lua.machine.workspaces")

-- 3. Look & feel
require("lua.hyprland.general")
require("lua.custom.general")
require("lua.hyprland.colors")

-- 4. Window / layer rules
require("lua.hyprland.rules")
require("lua.custom.rules")

-- 5. Autostart
require("lua.hyprland.execs")
require("lua.custom.execs")

-- 6. Keybinds (load last)
require("lua.hyprland.keybinds")
require("lua.custom.keybinds")
