# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Donwaztok
exec-once = solaar -w hide -b symbolic # logitech battery notification
# exec-once = gtk-launch vesktop
exec-once = gtk-launch zen
exec-once = gtk-launch com.rtosta.zapzap
# exec-once = QT_QPA_PLATFORM=wayland __GLX_VENDOR_LIBRARY_NAME=mesa zapzap --disable-gpu
exec-once = gtk-launch org.mozilla.Thunderbird