# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

windowrule = fullscreen on, match:class ^(steam_app_0)$, match:title ^(World of Warcraft)$
windowrule = no_anim noblur noborder, no_blur on, match:class ^(steam_app_0)$
windowrule = no_focus on, opacity 0, match:class ^(steam_app_0)$, match:title ^$