#!/usr/bin/env bash
# Sets image or video wallpaper for Hyprland. Theme colors are fixed (defaults/theme/colors.json in the shell).

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
SHELL_CONFIG_FILE="$XDG_CONFIG_HOME/donwaztok/config.json"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CUSTOM_DIR="$XDG_CONFIG_HOME/hypr/custom"
RESTORE_SCRIPT_DIR="$CUSTOM_DIR/scripts"
RESTORE_SCRIPT="$RESTORE_SCRIPT_DIR/__restore_video_wallpaper.sh"
THUMBNAIL_DIR="$RESTORE_SCRIPT_DIR/mpvpaper_thumbnails"
VIDEO_OPTS="no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no"

pre_process() {
    local mode_flag="$1"
    if [[ "$mode_flag" == "dark" ]]; then
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
        gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark' 2>/dev/null || true
    elif [[ "$mode_flag" == "light" ]]; then
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true
        gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3' 2>/dev/null || true
    fi
}

is_video() {
    local extension="${1##*.}"
    [[ "$extension" == "mp4" || "$extension" == "webm" || "$extension" == "mkv" || "$extension" == "avi" || "$extension" == "mov" ]] && return 0 || return 1
}

kill_existing_mpvpaper() {
    pkill -f -9 mpvpaper || true
}

create_restore_script() {
    local video_path=$1
    cat > "$RESTORE_SCRIPT.tmp" << EOF
#!/bin/bash
# Generated by switchwall.sh

pkill -f -9 mpvpaper

for monitor in \$(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "$VIDEO_OPTS" "\$monitor" "$video_path" &
    sleep 0.1
done
EOF
    mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
    chmod +x "$RESTORE_SCRIPT"
}

remove_restore() {
    cat > "$RESTORE_SCRIPT.tmp" << EOF
#!/bin/bash
# Placeholder — no video wallpaper restore.
EOF
    mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
}

set_wallpaper_path() {
    local path="$1"
    if [ -f "$SHELL_CONFIG_FILE" ]; then
        jq --arg path "$path" '.shell.background.wallpaperPath = $path' "$SHELL_CONFIG_FILE" > "$SHELL_CONFIG_FILE.tmp" && mv "$SHELL_CONFIG_FILE.tmp" "$SHELL_CONFIG_FILE"
    fi
}

set_thumbnail_path() {
    local path="$1"
    if [ -f "$SHELL_CONFIG_FILE" ]; then
        jq --arg path "$path" '.shell.background.thumbnailPath = $path' "$SHELL_CONFIG_FILE" > "$SHELL_CONFIG_FILE.tmp" && mv "$SHELL_CONFIG_FILE.tmp" "$SHELL_CONFIG_FILE"
    fi
}

# Same state file Quickshell Wallpapers service reads (~/.local/state/donwaztok/wallpaper/path.txt).
persist_wallpaper_state_path() {
    local path="$1"
    local st="${XDG_STATE_HOME}/donwaztok/wallpaper"
    mkdir -p "$st"
    printf '%s' "$path" > "${st}/path.txt"
}

apply_hyprpaper_static() {
    local path="$1"
    hyprctl hyprpaper preload "$path" 2>/dev/null || true
    while read -r monitor; do
        [[ -n "$monitor" ]] && hyprctl hyprpaper wallpaper "${monitor},${path}" 2>/dev/null || true
    done < <(hyprctl monitors -j | jq -r '.[] | .name')
}

categorize_wallpaper() {
    mkdir -p "$XDG_STATE_HOME/quickshell/user/generated/wallpaper"
    local img_cat
    img_cat=$("$SCRIPT_DIR/../ai/gemini-categorize-wallpaper.sh" "$1")
    echo "$img_cat" > "$XDG_STATE_HOME/quickshell/user/generated/wallpaper/category.txt"
}

check_and_prompt_upscale() {
    local img="$1"
    min_width_desired="$(hyprctl monitors -j | jq '([.[].width] | max)' | xargs)"
    min_height_desired="$(hyprctl monitors -j | jq '([.[].height] | max)' | xargs)"

    if command -v identify &>/dev/null && [ -f "$img" ]; then
        local img_width img_height
        if is_video "$img"; then
            img_width=$min_width_desired
            img_height=$min_height_desired
        else
            img_width=$(identify -format "%w" "$img" 2>/dev/null)
            img_height=$(identify -format "%h" "$img" 2>/dev/null)
        fi
        if [[ "$img_width" -lt "$min_width_desired" || "$img_height" -lt "$min_height_desired" ]]; then
            action=$(notify-send "Upscale?" \
                "Image resolution (${img_width}x${img_height}) is lower than screen resolution (${min_width_desired}x${min_height_desired})" \
                -A "open_upscayl=Open Upscayl" \
                -a "Wallpaper switcher")
            if [[ "$action" == "open_upscayl" ]]; then
                if command -v upscayl &>/dev/null; then
                    nohup upscayl > /dev/null 2>&1 &
                else
                    action2=$(notify-send \
                        -a "Wallpaper switcher" \
                        -c "im.error" \
                        -A "install_upscayl=Install Upscayl (Arch)" \
                        "Install Upscayl?" \
                        "yay -S upscayl-bin")
                    if [[ "$action2" == "install_upscayl" ]]; then
                        kitty -1 yay -S upscayl-bin
                        if command -v upscayl &>/dev/null; then
                            nohup upscayl > /dev/null 2>&1 &
                        fi
                    fi
                fi
            fi
        fi
    fi
}

switch_wallpaper() {
    local imgpath="$1"
    local mode_flag="$2"

    if [[ -z "$imgpath" || ! -e "$imgpath" ]]; then
        echo "No valid wallpaper path" >&2
        return 1
    fi

    if [ -f "$SHELL_CONFIG_FILE" ]; then
        aiStylingEnabled=$(jq -r '.shell.background.widgets.clock.cookie.aiStyling' "$SHELL_CONFIG_FILE")
        if [[ "$aiStylingEnabled" == "true" ]]; then
            categorize_wallpaper "$imgpath" &
        fi
    fi

    check_and_prompt_upscale "$imgpath" &
    kill_existing_mpvpaper

    if is_video "$imgpath"; then
        mkdir -p "$THUMBNAIL_DIR"

        missing_deps=()
        if ! command -v mpvpaper &> /dev/null; then
            missing_deps+=("mpvpaper")
        fi
        if ! command -v ffmpeg &> /dev/null; then
            missing_deps+=("ffmpeg")
        fi
        if [ ${#missing_deps[@]} -gt 0 ]; then
            echo "Missing deps: ${missing_deps[*]}"
            action=$(notify-send \
                -a "Wallpaper switcher" \
                -c "im.error" \
                -A "install_arch=Install (Arch)" \
                "Can't switch to video wallpaper" \
                "Missing dependencies: ${missing_deps[*]}")
            if [[ "$action" == "install_arch" ]]; then
                kitty -1 sudo pacman -S "${missing_deps[*]}"
            fi
            return 1
        fi

        set_wallpaper_path "$imgpath"

        local video_path="$imgpath"
        monitors=$(hyprctl monitors -j | jq -r '.[] | .name')
        for monitor in $monitors; do
            mpvpaper -o "$VIDEO_OPTS" "$monitor" "$video_path" &
            sleep 0.1
        done

        thumbnail="$THUMBNAIL_DIR/$(basename "$imgpath").jpg"
        ffmpeg -y -i "$imgpath" -vframes 1 "$thumbnail" 2>/dev/null
        if [ -f "$thumbnail" ]; then
            set_thumbnail_path "$thumbnail"
            create_restore_script "$video_path"
        else
            remove_restore
        fi
        persist_wallpaper_state_path "$imgpath"
    else
        set_wallpaper_path "$imgpath"
        set_thumbnail_path "$imgpath"
        remove_restore
        persist_wallpaper_state_path "$imgpath"
        apply_hyprpaper_static "$imgpath"
    fi

    if [[ -z "$mode_flag" ]]; then
        current_mode=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | tr -d "'")
        if [[ "$current_mode" == "prefer-dark" ]]; then
            mode_flag="dark"
        else
            mode_flag="light"
        fi
    fi
    pre_process "$mode_flag"
}

main() {
    imgpath=""
    mode_flag=""
    noswitch_flag=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --mode)
                mode_flag="$2"
                shift 2
                ;;
            --image)
                imgpath="$2"
                shift 2
                ;;
            --noswitch)
                noswitch_flag="1"
                imgpath=$(jq -r '.shell.background.wallpaperPath' "$SHELL_CONFIG_FILE" 2>/dev/null || echo "")
                shift
                ;;
            *)
                if [[ -z "$imgpath" ]]; then
                    imgpath="$1"
                fi
                shift
                ;;
        esac
    done

    if [[ -z "$imgpath" && -z "$noswitch_flag" ]]; then
        cd "$(xdg-user-dir PICTURES)/Wallpapers/showcase" 2>/dev/null || cd "$(xdg-user-dir PICTURES)/Wallpapers" 2>/dev/null || cd "$(xdg-user-dir PICTURES)" || exit 1
        imgpath="$(kdialog --getopenfilename . --title 'Choose wallpaper')"
    fi

    if [[ -n "$noswitch_flag" ]]; then
        exit 0
    fi

    switch_wallpaper "$imgpath" "$mode_flag"
}

main "$@"
